---
title: "in-class-template"
author: "sofia favela"
format: pdf
---

# 1. Set up

## Packages

```{r}
#| label: packages

# general use and cleaning
library(tidyverse)
library(here)
library(janitor)
library(snakecase)

# wrapping axis labels
library(scales)

# reading in .xlsx files
library(readxl)

# visualizing missing data
library(naniar)

# arranging plots
library(patchwork)
```

## Data

```{r}
#| label: data 

# taxonomic information
taxon_list <- read_csv(here("data", "taxon_list.csv"))

# aquatic invertebrates
aq_ins <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                    sheet = "Aquatic Insects") 

# site information
sites <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                   sheet = "sites")

# water quality information
water_quality <- read_xlsx(here("data", "Aquatic Sampling Data-2026-03-10.xlsx"),
                           sheet = "Water Quality",
                           na = c("", "n/a", "N/A", "over", "173+"))
```

# 2. Cleaning

## `sites` object

Goal: create a new object from `sites` that only includes NCOS sites

Use: filter downstream data frames using new objec

```{r}
#| label: ncos-site-object

# creating new object from sites
ncos_sites <- sites |> 
  # filter to only include NCOS quarterly sites 
  filter(sector == "NCOS" & sampling_frequency == "Quarterly")



```






  